### ISSUE TITLE
用json关联取值的时候，下一个接口引用的时候发送请求也是json

### ISSUE THREAD

**Issue by rocal10** [Chras-fu/Liuma-platform#10]
![image](https://user-images.githubusercontent.com/69668754/190545717-abce0ee5-a3c2-4439-970d-06d79b3f3a76.png)
请求是get，和表单格式结果点击调试的时候发送的是json格式
![image](https://user-images.githubusercontent.com/69668754/190545910-109469b3-c981-4ddf-8a5d-4c6f75d3f1f0.png)

**Comment by Chras-fu** [comment]
GET请求使用QUERY参数入参

**Comment by rocal10** [comment]
![image](https://user-images.githubusercontent.com/69668754/190619605-df3d25fa-7681-44c1-b25c-34c03bc6acaf.png)
试了用query参数 作为入参 还是请求的json

**Comment by rocal10** [comment]
> GET请求使用QUERY参数入参

![image](https://user-images.githubusercontent.com/69668754/190619890-e1dbf1ae-3652-42f8-a0f9-44728c33c2af.png)
试了用查询参数作为入参还是请求的json

**Comment by rocal10** [comment]
> 使用了query参数，发送请求的时候还是json
![image](https://user-images.githubusercontent.com/69668754/190620176-1714d958-3e4f-421e-b9e3-3816079b2cfb.png)

![image](https://user-images.githubusercontent.com/69668754/190620302-bd27a8cd-968e-4fbe-805e-86abe0ce33cd.png)

**Comment by Chras-fu** [comment]
这里显示json并不影响请求，可以参考python requests包的具体用法。
至于报错，是因为当前不支持请求体中选择非json但又不填实际数据，把请求体类型改为json即可。
该问题会在后续版本兼容。
