### ISSUE TITLE
接口返回大量json数据的时候，页面会没有响应，运行日志报500

### ISSUE THREAD

**Issue by rocal10** [Chras-fu/Liuma-platform#11]
![image](https://user-images.githubusercontent.com/69668754/190546907-dd2cd9c8-287c-4d60-80c6-4f1a52f8327d.png)

**Comment by Chras-fu** [comment]
版本问题。等1.1发布或者执行一下SQL
ALTER TABLE `report_collection_case_api` MODIFY `exec_log` longtext;
