### ISSUE TITLE
请求头 Content-Type一直为application/json

### ISSUE THREAD

**Issue by xinxinwx** [Chras-fu/Liuma-platform#16]
![1666345393126](https://user-images.githubusercontent.com/34635282/197166227-f9ec9e19-bc9b-4ec5-ae07-2cff26449829.jpg)
![1666345452434](https://user-images.githubusercontent.com/34635282/197166409-2d666eb8-41e0-4d9f-83bf-23a386d8d66f.jpg)
选项from-data或者xx-www-from-urlencoded场景下  请求头一直为 {"Content-Type": "application/json;charset=UTF-8"}

**Comment by Chras-fu** [comment]
请求头为空时默认为json，如需其他类型请求头，需要在请求头中自行维护content-type
