### ISSUE TITLE
新增web用例编辑页面，在配置信息中增加“复用本地浏览器”（非必填）

### ISSUE THREAD

**Issue by Leofighting** [Chras-fu/Liuma-platform#19]
Web系统的操作普遍基于登录状态下进行操作，
甚至登录时需要填写图片、短信验证码，
若能复用本地浏览器，利用浏览器缓存，可以跳过登录步骤，直达对应的页面，大大减少不必要的用例步骤。

具体实现如下图所示，新增/编辑 Web用例页面中个，在配置信息中增加“复用本地浏览器”（非必填）：
![image](https://user-images.githubusercontent.com/49736670/203886271-0ffe8a71-8ec8-412d-b4e9-9c85c2da9eda.png)

**Comment by Chras-fu** [comment]
1.2版本该需求已完成
