### ISSUE TITLE
能否自动提取拼接响应路径，不用手动做提取数据，自动帮我做了，变量就是对应的json的key，我只要获取key的变量名，就可以得到我要提取的jsonpath的值了，省的做接口依赖的时候需要一个一个去获取依赖的值

### ISSUE THREAD

**Issue by cfy3133** [Chras-fu/Liuma-platform#2]
![image](https://user-images.githubusercontent.com/43978367/173504362-ad4995f1-d58f-452c-88e2-8eba331878cc.png)

**Comment by Chras-fu** [comment]
谢谢建议，已实现该功能，可以前往demo环境体验
