### ISSUE TITLE
新增控件，“控件名称”过长，保存失败，提示信息

### ISSUE THREAD

**Issue by Leofighting** [Chras-fu/Liuma-platform#21]
![Snipaste_2022-12-14_14-16-33](https://user-images.githubusercontent.com/49736670/207521221-2609deef-93f6-423e-b736-5842f0c10271.png)
1. 控件名称 输入：check_element_text_and_click
2. 其他正常输入
3. 点击【保存】
报错提示：Request failed with status code 500
后台日志：
![image](https://user-images.githubusercontent.com/49736670/207522038-cc7aba25-32e5-453c-b528-dd28aaf62102.png)

**Comment by Chras-fu** [comment]
这个字段设计最长二十个字符，当时主要考虑用中文命名，后面调大点。你可以自行修改该字段的长度
