### ISSUE TITLE
测试报告增加一个状态的筛选

### ISSUE THREAD

**Issue by rocal10** [Chras-fu/Liuma-platform#22]
![54dc911876031b736b0b23563f3825e](https://user-images.githubusercontent.com/69668754/220586091-7468d366-27e1-406b-9dec-d89dd97c27ae.png)

**Comment by rocal10** [comment]
可以筛选 成功，失败，断言失败等状态

**Comment by Chras-fu** [comment]
企业版支持该功能，可以前往体验：[链接](http://demo-ee.liumatest.cn)
