### ISSUE TITLE
这个接口测试平台有几个不错的功能特性，看能不能借鉴借鉴

### ISSUE THREAD

**Issue by bitlin** [Chras-fu/Liuma-platform#26]
https://gitee.com/qu-niao/LessIsMore.git

**Comment by Chras-fu** [comment]
从自述文件中没看到你说的特性，能否大概讲一下是哪些特性？

**Comment by bitlin** [comment]
目前看主要是前端接口编辑的交互和更灵活的页面中Python编码支持

接口编辑和执行时，双击接口返回结果的某个字段行，可以自动添加到结果校验或者变量提取部分，简化了输入的麻烦
![image](https://user-images.githubusercontent.com/14798891/229478607-30ea9fcc-f686-4fd8-a9eb-b3b333187396.png)

**Comment by Chras-fu** [comment]
这个功能很早之前就有了,可以看使用手册具体了解一下，只是表现方式不一样，我是把JSON解析了做一键添加
![image](https://user-images.githubusercontent.com/96771570/229482899-ba64efbe-d80a-4d57-9093-0276f6b1af47.png)
