### ISSUE TITLE
执行用例，接口维护的header没有获取到

### ISSUE THREAD

**Issue by Casers** [Chras-fu/Liuma-platform#3]
![image](https://user-images.githubusercontent.com/29518335/178764376-352920b5-a786-47f0-8ed6-834d61f2c216.png)
这里的通过用例id获取用例和接口列表，其中header属性body属性query属性是不是映射错误了？

**Comment by Chras-fu** [comment]
不是映射错误，这里确实需要取case_api表。造成你这个问题主要是用例编写时，选了接口后需要对接口进行编辑，这样才能带出接口的属性，之所以这样做是希望写用例时必须编辑加断言，很多人写用例都加了接口就直接跑，这样没有意义。如果不编辑直接保存或者调试，确实会出现你这个情况。

**Comment by Casers** [comment]
好的  明白了
