### ISSUE TITLE
前端用例编辑界面修改接口添加关联取值报错

### ISSUE THREAD

**Issue by Casers** [Chras-fu/Liuma-platform#4]
![image](https://user-images.githubusercontent.com/29518335/178765930-7591bd88-2a0a-4cee-913d-3f9de6723c26.png)
这里子组件直接修改父组件传递过来的值时会报错，导致前端新增关联取值按钮点击没有反应

**Comment by Chras-fu** [comment]
我没能复现你这个问题，代码这样写本身是没有问题的，报错原因可能是relation字段父组件传了null值过来，但父组件我已对该值做了初始化处理。希望能提供一下详细的复现步骤，如果回复述说不清，也可以进微信群交流，在官网最下方和微信公众号 均有群聊二维码。

**Comment by Casers** [comment]
![image](https://user-images.githubusercontent.com/29518335/178886345-c22769cd-104b-4457-a6bf-d50241264543.png)
![image](https://user-images.githubusercontent.com/29518335/178886465-353e6aaf-92a8-4696-ad9a-5860daf06ab5.png)
我打印了下父组件传进来的relation字段还是null值。
1、我是初始化系统，新建了一个接口
2、然后新增用例在用例里面添加刚新增的接口
3、保存用例
4、编辑用例，编辑里面的接口，选择关联取值，点击新增，然后就会报错

**Comment by Chras-fu** [comment]
因改动后端sql所致，已沟通解决

**Comment by Chras-fu** [comment]
因改动后端sql所致，已沟通解决
