### ISSUE TITLE
接口请求体中带有中文代码异常无法执行

### ISSUE THREAD

**Issue by Binice5213** [Chras-fu/Liuma-platform#7]
<img width="583" alt="image" src="https://user-images.githubusercontent.com/91314999/188424821-322076ba-4e2e-4ecf-9e02-8cf510316037.png">

请求体内容：
{
  "operationDesc": "MySQl应用连接检查",
  "operationMark": "mysql_check_app_connection",
  "commonMysqlsSerivceItems": [
    {
      "clusterId": "1282590122105114720",
      "arcType": "HA",
      "name": "hatest2022080101"
    }
  ]
}

**Comment by Chras-fu** [comment]
请求体内容贴一下

**Comment by Chras-fu** [comment]
我用demo环境没有出现这种错误，请求体怎么设置的。最好提供完整的请求日志

**Comment by Binice5213** [comment]
<img width="609" alt="image" src="https://user-images.githubusercontent.com/91314999/188427609-1407fba7-d208-4914-aac3-d41455f23d18.png">

**Comment by Chras-fu** [comment]
问题已经定位，当请求体类型为raw时，目前确实不支持中文。
针对你的情况，参考你的content-type选择为application/json，那么你的请求体类型应该选择为json而不是raw。
如果该接口确实是text类型，那么需要你先修改请求头中的content-type，另外将以下两行代码加到引擎/core/api/teststep.py文件55-56行，即可使用。该问题会在下个版本修复。
![image](https://user-images.githubusercontent.com/96771570/188432460-1211f97d-8035-4932-8ee8-b4db95d8db13.png)
