### ISSUE TITLE
切换项目后，创建同名的函数和接口名称都会提示重复，数据不隔离？

### ISSUE THREAD

**Issue by rocal10** [Chras-fu/Liuma-platform#8]

**Comment by Chras-fu** [comment]
项目间数据是隔离的，但函数名重复校验先前的设计确实是针对整个系统的，在1.1版本发布后会转为项目内校验，请耐心等待。
接口管理没做过重复校验，无论是否同一项目，请检查下操作或者提供下完整的复现步骤。

**Comment by Chras-fu** [comment]
1.0.3版本已经支持不同项目新建相同函数名，可更新查看
