### ISSUE TITLE
自定义的函数调用不了，报错

### ISSUE THREAD

**Issue by rocal10** [Chras-fu/Liuma-platform#9]
![1663063150914](https://user-images.githubusercontent.com/69668754/189872678-53453bcf-317c-49c2-a4b6-be6e5b79d1e3.jpg)
![image](https://user-images.githubusercontent.com/69668754/189872779-b640c7f3-5de2-4c9f-9832-48b923da5000.png)
自定义写的函数无法调用  报错

![image](https://user-images.githubusercontent.com/69668754/189872963-eef25bfd-a021-473e-a05b-fbf8c4158c96.png)
请求头格式 Content-Type: application/x-www-form-urlencoded
![image](https://user-images.githubusercontent.com/69668754/189873473-7980de18-a4b1-4e90-996c-a8d687426ebc.png)

**Comment by Chras-fu** [comment]
自定义函数需要使用前在用例配置中导入，请检查是否导入该函数。
如果问题已解决，请给作者点个star，谢谢
